import os

DLO_DIR = os.environ['USERPROFILE'] + '/OneDrive - The University of Nottingham/Documents/DLO/'
SS_SERVICES = '/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=99114A96025D4D768FB7BF3BC9DB1D36-SS-ASSESS-S'
MEL = ''